name: CI

on:
  push:
    branches: [main, develop, feature/setup-docker]
  pull_request:
    branches: [main, develop, feature/setup-docker]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 pytest

      - name: Run Lint (black & flake8)
        run: |
          black app/main.py --check
          flake8 app/main.py
